begin;

create table if not exists public.guestbook_messages (
  id bigint generated by default as identity primary key,
  nickname text not null check (char_length(nickname) between 1 and 30),
  content text not null check (char_length(content) between 1 and 500),
  ip text not null,
  created_at timestamptz not null default now(),
  likes bigint not null default 0 check (likes >= 0),
  pinned boolean not null default false,
  parent_id bigint references public.guestbook_messages(id) on delete cascade
);

create index if not exists guestbook_messages_parent_created_idx
  on public.guestbook_messages (parent_id, created_at);

alter table public.guestbook_messages enable row level security;
revoke all on table public.guestbook_messages from anon, authenticated;

-- Public visitors never access this table directly. Vercel Route Handlers use
-- the server-only service-role key and return only the fields needed by the UI.

commit;
